# Generated by Django 4.2 on 2025-07-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_genericplayer'),
        ('room', '0002_alter_room_description_alter_room_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_count', models.IntegerField(default=0)),
                ('purse', models.IntegerField(default=0)),
                ('is_user', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_state', to='room.room')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_state', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team State',
                'verbose_name_plural': 'Team States',
            },
        ),
        migrations.CreateModel(
            name='AuctionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player_type', models.CharField(max_length=255)),
                ('nationality', models.CharField(choices=[('INDIAN', 'INDIAN'), ('OVERSEAS', 'OVERSEAS')], max_length=255)),
                ('base_price', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('UNSOLD', 'UNSOLD'), ('SOLD', 'SOLD')], default='PENDING', max_length=255)),
                ('current_bid', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(default=0)),
                ('current_bid_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid_team', to='teams.team')),
                ('final_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_team', to='teams.team')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
            options={
                'verbose_name': 'Auction Player',
                'verbose_name_plural': 'Auction Players',
            },
        ),
    ]
