# Generated by Django 4.2 on 2025-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_teamstate_auctionplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionplayer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('UNSOLD', 'UNSOLD'), ('SOLD', 'SOLD')], default='PENDING', max_length=255),
        ),
    ]
