# Generated by Django 4.2 on 2025-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_auctionplayer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionplayer',
            name='batting_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auctionplayer',
            name='bowling_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auctionplayer',
            name='overall_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionplayer',
            name='personality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
