# Generated by Django 4.2 on 2025-07-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auctionplayer_created_auctionplayer_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionplayer',
            name='current_bid_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid_team', to='room.teamstate'),
        ),
        migrations.AlterField(
            model_name='auctionplayer',
            name='final_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_team', to='room.teamstate'),
        ),
    ]
