# Generated by Django 4.2 on 2025-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player_type', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, choices=[('INDIAN', 'INDIAN'), ('OVERSEAS', 'OVERSEAS')], max_length=255, null=True)),
                ('base_price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
